### PR TITLE
Fix some HTML errors

### PR DESCRIPTION
**Pull request by tripu**

### CODE REVIEW

**Comment by tripu** [comment]
@lcarcone, these should be fairly simple changes, hopefully nothing controversial.

**Comment by lcarcone** [comment]
Hi Tripu,

Just quick comments:
- I think we shouldn't modify the structure of files index.html and qtypes.html as they should stay the sames as the current version of wbs on w3c site. (btw, the 'edit' icon of 'old' pages has been changed, likely with my modifs, we should restore the old icon for those pages)
- For new files, ok to change the doctype (I didn't change it as I wanted to check with Dom first but I'll check later)
- For qtypes-site.html, the end div '</div> ' is part of the w3c template, don't remove it, the error comes from the missing '<div id="Content">' (the structure of the file index-site-select2.html is correct and should be used for new files now)
- For the moment, keep 'border='1'' for tpac table, we'll remove it when we have even/odd style for that table 

Thank you
Laurent

**Comment by tripu** [comment]
@lcarcone:

> I think we shouldn't modify the structure of files index.html and qtypes.html as they should stay the sames as the current version of wbs on w3c site. (btw, the 'edit' icon of 'old' pages has been changed, likely with my modifs, we should restore the old icon for those pages)

Yes, sorry! I've reverted those files in this branch. (And now I'm afraid that I may have been editing those two files in other recent branches, too).

> For new files, ok to change the doctype (I didn't change it as I wanted to check with Dom first but I'll check later)

OK. I don't see why changing the _doctype_ would be a bad thing, but perhaps I'm missing something.

> For qtypes-site.html, the end div `</div> <!-- /end #w3c_container -->` is part of the w3c template, don't remove it, the error comes from the missing `<div id="Content">` (the structure of the file index-site-select2.html is correct and should be used for new files now)

Sorry, I don't understand this. `div`s don't match if you don't remove that one, right? Either there's a `<div>` missing somewhere, or that `</div>` is unnecessary. No?

> For the moment, keep 'border='1'' for tpac table, we'll remove it when we have even/odd style for that table

Why not edit CSS to add the striped pattern already, instead of dragging that deprecated `border` property any longer?

**Comment by lcarcone** [comment]
Le 09/03/2016 09:24, tripu a écrit :

> @lcarcone https://github.com/lcarcone:
> 
> ```
> I think we shouldn't modify the structure of files index.html and
> qtypes.html as they should stay the sames as the current version
> of wbs on w3c site. (btw, the 'edit' icon of 'old' pages has been
> changed, likely with my modifs, we should restore the old icon for
> those pages)
> ```
> 
> Yes, sorry! I've reverted those files in this branch. (And now I'm 
> afraid that I may have been editing those two files in other recent 
> branches, too).
> 
> ```
> For new files, ok to change the doctype (I didn't change it as I
> wanted to check with Dom first but I'll check later)
> ```
> 
> OK. I don't see why changing the /doctype/ would be a bad thing, but 
> perhaps I'm missing something.
> 
> ```
> For qtypes-site.html, the end div ' '
> is part of the w3c template, don't remove it, the error comes from
> the missing |<div id="Content">| (the structure of the file
> index-site-select2.html is correct and should be used for new
> files now)
> ```
> 
> Sorry, I don't understand this. |div|s don't match if you don't remove 
> that one, right? Either there's a |<div>| missing somewhere, or that 
> |</div>| is unnecessary. No?

There is an extra </div> line 503 (after See also <a href='access'>who 
can do what</a> with this questionnaire), please remove that one.

> ```
> For the moment, keep 'border='1'' for tpac table, we'll remove it
> when we have even/odd style for that table
> ```
> 
> Why not edit CSS to add the striped pattern already, instead of 
> dragging that deprecated |border| property any longer?

OK to remove it, I'll work on the css for that table. I'll also change 
the content as the actual tables for tpac contain in general ' Not 
Member confidential' and ' (with Chair's agreement)' for options ' 
Confidentiality' and ' Observer request'

Thanks,
Laurent

**Comment by tripu** [comment]
> There is an extra </div> line 503 (after See also <a href='access'>who can do what</a> with this questionnaire), please remove that one.

(~~503~~ 530, right?)
OK, now I got it! [Fixed](https://github.com/w3c/wbs-design/commit/42bf563deef898fa732b4389acc3a4fc9a20a0f2#diff-8b451e36e71be8c1fc6ea86cfd624009), thanks :)

> OK to remove it, I'll work on the css for that table. I'll also change the content as the actual tables for tpac contain in general ' Not Member confidential' and ' (with Chair's agreement)' for options ' Confidentiality' and ' Observer request'

Great, I think that's better.

I think now it's ready to merge, then.

**Pull request merged**
