### PR TITLE
rough demo of hide/show left column menu

### PR DESCRIPTION
**Pull request by lcarcone**
Hi,

This is just a demo to see how the left menu can be shown or hidden (the js code needs improvements / clean up)

### CODE REVIEW

**Review by tripu — CHANGES_REQUESTED** [review]
@lcarcone, I think you missed changes to HTML files? eg, loading the new JS file from one or several pages, adding that `#leftCol_img` element, etc? Otherwise, it's not clear where this applies, or how to use it&hellip;

**Comment by lcarcone** [comment]
@tripu,  I forgot to commit the result page (qtypes-site-results.html). I tested the demo for this page only for the moment.
Thanks

**Comment by tripu** [comment]
@lcarcone, I see now, thanks.

I like the idea. A couple of suggestions:

* Add a rule like `#leftCol_menu a:hover { background-color: inherit; }` to avoid that coloured background on mouse over.
* When the menu is collapsed, keep the cross visible upon scroll. eg: `div#leftCol_menu { position: fixed; left: 20px; top: 100px; }` (we'll have to work out the exact position).

**Comment by lcarcone** [comment]
@tripu, I like the idea too !
In fact, I worked on it because people complained that there was  too much unused space, making the results more difficult to read. I think it can help to read large tables particularly.
I have added the 2 rules you recommended. Btw, I didn't get the 'coloured background on mouse over', I tested on Firefox and Chrome.
For the cross, I think it's a bit weird to have it fixed near the middle of the page when the menu has been scrolled. I tested with a fixed menu too but I'm not happy with it. W3C pages should have a top fixed menu in the next template I think. One thing we could do is to fix the cross only when it is near the top of the page (using topscroll). But we can do that later, for the moment let's merge the request as this so that people can test it.

Thanks,
Laurent

**Review by tripu — APPROVED** [review]

**Comment by tripu** [comment]
@lcarcone,

that coloured background when I hover over the icons has disappeared for me, thanks.

We still have the issue of where exactly to place the icons when scrolling, yes. But as you prefer to have it merged for early testing and feedback, let's do that first.

**Pull request merged**
