### PR TITLE
Update footer of pages

### LINKED ISSUE #38: Update footer of pages (?)
Currently there is this notice at the bottom of pages:

> *Maintained by Laurent Carcone, from a development by <a href="/People/Dom/">Dominique Hazaël-Massieux</a> (<a href="mailto:dom@w3.org">dom@w3.org</a>) on an <a href="/2000/11/msm/">original design</a> by <a href="/People/cmsmcq/">Michael Sperberg-McQueen</a> <em>$Id: vote.php3,v 1.373 2017/08/16 19:56:22 antonio Exp $</em>. Please send bug reports and request for enhancements to <a href="mailto:lcarcone@w3.org">lcarcone@w3.org</a> with <a href="mailto:w3t-sys@w3.org">w3t-sys@w3.org</a> copied (if your mail client supports it, <a href="mailto:lcarcone@w3.org(Laurent%20Carcone),w3t-sys@w3.org(Systems Team)?subject=WBS%20bug%20report%20">send mail</a> directly to the right persons)*

Don't we want to update that? eg, relieving @lcarcone and the Systeam ML, and directing all feedback to  Sysreq instead.

### PR DESCRIPTION
**Pull request by tripu**
Fixes #38

### CODE REVIEW

**Comment by lcarcone** [comment]
Hi,
I'm fine with the removal of my name in the footer, have you checked with Dom ?
Maybe we should create a new github repository to get more generic requests as 'wbs-design' can be confusing.
Also having 2 systems to get requests may be a bit more difficult to manage as some people won't use a github account to report a problem (just a thought).

Thanks

**Comment by tripu** [comment]
> *&ldquo;I'm fine with the removal of my name in the footer, have you checked with Dom?&rdquo;*

Good point. I assumed anyone would be happy to be relieved of having to respond to issues personally. But it's true that the footer serves another purpose: to acknowledge the author.

What do you think @dontcallmedom?

> *&ldquo;Maybe we should create a new github repository to get more generic requests as 'wbs-design' can be confusing.&rdquo;*

I don't think we need two repos. This is just something that popped up while we were evaluating our recent changes&hellip;

> *&ldquo;Also having 2 systems to get requests may be a bit more difficult to manage as some people won't use a github account to report a problem (just a thought).&rdquo;*

GitHub is the most useful means nowadays, IMO. The e-mail address is there for the (few) cases when the reporter doesn't have a GH account.

**Comment by dontcallmedom** [comment]
I don't feel strongly either way - acks are a good way to create both praise and blame opportunities (which I think is good), but we should also align with what other tools do in that regard.

**Comment by tripu** [comment]
Looking at the footers on recent tools (Echidna, Specberus, Ash-Nazg, Unitas) I don't see names; only copyright notices pointing to W3C, and GH repos. I'd go for that in WBS, too; for consistency. (Not to diminish anyone's contribution to the tool!)

**Pull request merged**
